steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - us-central1-docker.pkg.dev/$PROJECT_ID/aswathy-docker-repo/hello-docker:$SHORT_SHA
      - '.'

  # Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - us-central1-docker.pkg.dev/$PROJECT_ID/aswathy-docker-repo/hello-docker:$SHORT_SHA

  # Set up kubectl (configure cluster access)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials hello-cluster --zone us-central1-a

  # Deploy to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - apply
      - '-f'
      - k8s/deployment.yaml

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - apply
      - '-f'
      - k8s/service.yaml

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/hello-docker:$SHORT_SHA
